[QUEUE]
# Do you want to use Slurm?
USE_SLURM = True
# GPU ID to be used when Slurm is set up and you do want to skip it
GPU_ID_SKIP_SLURM = 7
# Queue names
STANDARD_QUEUE_NAME = standard
PRIORITY_QUEUE_NAME = fast

[CHIMERA]
MAX_MEM_TO_USE = 60000
MAX_VOXELS = 1500

[INTERMEDIATE_DATA]
STORE_INTERMEDIATE_DATA = True
CLEAN_ORIGINAL_DATA = True
DEST_PATH = /data/ScipionUserDataToRetrieve/projects

[MAPQ]
MAPQ_PATH = /home/vrs/scipion3/software/em/chimera-1.16/mapq/
CHIMERA_PROGRAM_PATH = /home/vrs/scipion3/software/em/chimera-1.16/chimera/bin/chimera

[EM-VALIDATION]
VALIDATION_TOOLS_PATH = /home/vrs/scipion3/scipion-em-validation/tools/
VALIDATION_SERVER_LAUNCHER = /home/vrs/scipion3/scipion-em-validation/validationLevels.py

[EMDB]
ENTRIES_PATH = /home/vrs/EMDB/entries
SQLITE_DDBB_PATH = /home/vrs/EMDB/database/vrs.db
LOG_PATH = /home/vrs/EMDB/logs

[SCIPION]
SCIPIONPROJECTS_PATH = /home/vrs/ScipionUserData/projects
SCIPION_LAUNCHER = /home/vrs/scipion3/scipion3