import os
import time
import json
import subprocess
from pyworkflow.object import Boolean
from pyworkflow.protocol import getProtocolFromDb
import configparser

config = configparser.ConfigParser()
config.read([os.path.join(os.path.dirname(__file__), 'config.yaml'), os.path.join(os.path.dirname(__file__), 'config_dev.yaml')])
standard_queue = os.getenv('QUEUE_STANDARD_QUEUE_NAME') or config['QUEUE'].get('STANDARD_QUEUE_NAME')
priority_queue = os.getenv('QUEUE_PRIORITY_QUEUE_NAME') or config['QUEUE'].get('PRIORITY_QUEUE_NAME')
if os.getenv('QUEUE_NODE_LIST'):
  node_list = os.getenv('QUEUE_NODE_LIST')
elif config['QUEUE'].getboolean('USE_SPECIFIC_NODES'):
  node_list = config['QUEUE'].get('NODE_LIST')
else:
  node_list = None

#TODO: add function to set whether the user wants to use slurm or not

BYTES_PER_VOXEL = 4  # EMDB maps are stored as float32
MEMORY_SAFETY_FACTOR = 3  # headroom for copies made while downloading/importing
MAX_IMPORT_MEMORY_MB = 131072  # 128 GB hard cap, never request more than this

def computeImportMemory(col, row, sec, base_memory=8192):
  """
  Estimates the Slurm memory (in MB) needed to import an EMDB map
  """
  if not (col and row and sec):
    return base_memory

  voxels = col * row * sec
  estimated_mb = (voxels * BYTES_PER_VOXEL * MEMORY_SAFETY_FACTOR) / (1024 ** 2)
  if estimated_mb <= base_memory:
    return base_memory

  memory = int(estimated_mb)
  if memory > MAX_IMPORT_MEMORY_MB:
    print("WARNING: estimated import memory (%d MB) for a %dx%dx%d map exceeds "
          "the %d MB cap, using the cap instead" % (memory, col, row, sec, MAX_IMPORT_MEMORY_MB))
    memory = MAX_IMPORT_MEMORY_MB
  return memory

# MB per atom for Phenix's cryo-EM validation/fitting-check step (phenixExecution() in
# validationLevelA.py), which until now was sent to Slurm with the flat 8192 MB default
# regardless of model size. Calibrated from two direct reproductions of EMD-70833's real
# map (560^3 voxels) and model (9OTI, 43325 atoms) run standalone (outside Slurm, so
# uncapped): observed peak RSS was ~5.9 GB (~0.136 MB/atom). We round that up with margin,
# since memory usage varied noticeably between the two reproductions (raw vs
# PDBFixer-processed model) for the same entry, and we only have data points at one map
# size - this should be revisited once more entries have gone through it in production
# (see fixes/005-phenix-oom-silent-levela-skip.md).
PHENIX_MB_PER_ATOM = 0.2
PHENIX_MEMORY_SAFETY_FACTOR = 2

def computePhenixMemory(numAtoms, col=None, row=None, sec=None, base_memory=8192):
  """
  Estimates the Slurm memory (in MB) needed for Phenix's cryo-EM validation protocol.
  Memory usage is dominated by the atomic model, not by the map (a 560^3 map alone only
  needs ~2 GB per computeImportMemory), so this scales primarily with atom count; the
  map-size estimate is kept only as a floor.
  """
  memory = computeImportMemory(col, row, sec, base_memory=base_memory) if (col and row and sec) else base_memory
  if numAtoms:
    estimated_mb = int(numAtoms * PHENIX_MB_PER_ATOM * PHENIX_MEMORY_SAFETY_FACTOR)
    memory = max(memory, estimated_mb)
  if memory > MAX_IMPORT_MEMORY_MB:
    print("WARNING: estimated Phenix memory (%d MB) for %s atoms exceeds the %d MB cap, "
          "using the cap instead" % (memory, numAtoms, MAX_IMPORT_MEMORY_MB))
    memory = MAX_IMPORT_MEMORY_MB
  return memory

def waitOutput(project, prot, outputAttributeName, sleepTime=10, timeOut=432000):
  """ Wait until the output is being generated by the protocol. """

  def _loadProt():
    # Load the last version of the protocol from its own database
    loadedProt = getProtocolFromDb(prot.getProject().path,
                                   prot.getDbPath(),
                                   prot.getObjId())
    # Close DB connections
    loadedProt.getProject().closeMapper()
    loadedProt.closeMappers()
    return loadedProt

  counter = 1
  prot2 = _loadProt()

  numberOfSleeps = timeOut / sleepTime

  while (not prot2.hasAttribute(outputAttributeName)) and prot2.isActive():
    time.sleep(sleepTime)
    prot2 = _loadProt()
    if counter > numberOfSleeps:
      print("Timeout (%s) reached waiting for %s at %s" % (timeOut, outputAttributeName, prot))
      break
    counter += 1

  # Update the protocol instance to get latest changes
  project._updateProtocol(prot)

def waitOutputFile(project, prot, outputFileName, sleepTime=10, timeOut=432000):
  """ Wait until the output file is being generated by the protocol. """
  def _loadProt():
    # Load the last version of the protocol from its own database
    loadedProt = getProtocolFromDb(prot.getProject().path,
                                   prot.getDbPath(),
                                   prot.getObjId())
    # Close DB connections
    loadedProt.getProject().closeMapper()
    loadedProt.closeMappers()
    return loadedProt

  counter = 1
  prot2 = _loadProt()

  numberOfSleeps = timeOut / sleepTime
  while (not os.path.exists(os.path.join(project.getPath(), prot2._getExtraPath(outputFileName)))) and prot2.isActive():
    time.sleep(sleepTime)
    prot2 = _loadProt()
    if counter > numberOfSleeps:
      print("Timeout (%s) reached waiting for %s at %s" % (timeOut, outputFileName, prot))
      break
    counter += 1

def waitUntilFinishes(project, prot, sleepTime=10, timeOut=432000):
  """ Wait until the protocol finishes. """

  def _loadProt():
    # Load the last version of the protocol from its own database
    loadedProt = getProtocolFromDb(prot.getProject().path,
                                   prot.getDbPath(),
                                   prot.getObjId())
    # Close DB connections
    loadedProt.getProject().closeMapper()
    loadedProt.closeMappers()
    return loadedProt

  counter = 1
  prot2 = _loadProt()

  numberOfSleeps = timeOut / sleepTime

  while not prot2.isFinished() and not prot2.isFailed() and not prot2.isAborted():
    time.sleep(sleepTime)
    prot2 = _loadProt()
    if counter > numberOfSleeps:
      print("Timeout (%s) reached waiting for %s to finish" % (timeOut, prot))
      break
    counter += 1

  # Update the protocol instance to get latest changes
  project._updateProtocol(prot)

#TODO: allow the user to add parameters (e.g. prot.gpuList.set(7))

def sendToSlurm(prot, memory=8192, hours=48, GPU=False, nGPUs=1, nMPIs=None, nThreads=None, priority=False):
    prot._useQueue.set(Boolean(True))
    QUEUE_PARAMS = (priority_queue if priority else standard_queue, {'JOB_MEMORY': memory, 'JOB_TIME': hours, 'GPU_COUNT': nGPUs if GPU else 0, 'JOB_NODES': nMPIs if nMPIs else int(prot.numberOfMpi), 'JOB_THREADS': nThreads if nThreads else int(prot.numberOfThreads)})
    prot._queueParams.set(json.dumps(QUEUE_PARAMS))

def skipSlurm(prot, GPUId):
    prot._useQueue.set(Boolean(False))
    prot.gpuList.set(GPUId)

def createScriptForSlurm(jobname, path, command, nTasks=1, cpusPerTask=1, memory=8192, nGPUs=0, hours=48, priority=False):
  script = """#!/bin/bash
#SBATCH --export=ALL
#SBATCH -J %s
#SBATCH -o %s
#SBATCH -e %s
#SBATCH --open-mode=append
%s
#SBATCH -p %s
#SBATCH --time=%d:00:00 --ntasks=%d --cpus-per-task=%d --mem=%d --gres=gpu:%d
  
%s""" % (jobname,
         os.path.join(path, jobname + '.job.out'),
         os.path.join(path, jobname + '.job.err'),
         f'#SBATCH --nodelist={node_list}' if node_list else '',
         priority_queue if priority else standard_queue,
         hours, nTasks, cpusPerTask, memory, nGPUs, command)
  with open(os.path.join(path, jobname + '.sh'), 'w') as archivo:
    archivo.write(script)
  return os.path.join(path, jobname + '.sh')

def checkIfJobFinished(jobname):
  command = 'squeue -o "%.500j"'
  process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
  output, _ = process.communicate()
  output = output.decode('utf-8')

  return jobname not in output