######################### METHOD NAME CONSTANTS #########################
NAME_DEEPRES = "DeepRes"
NAME_LOCBFACTOR = "LocBfactor"
NAME_LOCOCCUPANCY = "LocOccupancy"
NAME_DEEPHAND = "DeepHand"
NAME_GLOBAL_RES = "Global resolution"
NAME_FSC_PERMU = "FSC permutation"
NAME_BLOCRES = "Blocres"
NAME_MONORES = "MonoRes"
NAME_MONODIR = "MonoDir"
NAME_FSO = "FSO"
NAME_FSC3D = "FSC3D"
NAME_COMPARE_PROJECTIONS = "Compare reprojections"
NAME_OUTLIER_DETECTION = "Outlier detection"
NAME_CORE_ANALYSIS = "Core analysis"
NAME_CLASSIFICATION_EXT_CONSISTENCY = "Classification external consistency"
NAME_SIMILARITY_CRITERIA = "Similarity criteria"
NAME_ALIGN_SMOOTHNESS =  "Alignability smoothness"
NAME_ALIGNABILITY = "Alignability"
NAME_RELION_ALIGN = "Relion alignment"
NAME_CRYOSPARC_ALIGN = "CryoSparc alignment"
NAME_RELION_CRYOSPARC_ALIGN = "Relion/CryoSparc alignments"
NAME_CLASSIFICATION_WITHOUT_ALIGN = "Classification without alignment"
NAME_OVERFITTING_DETECT = "Overfitting detection"
NAME_ANGULAR_DISTR_EFFICIENCY = "Angular distribution efficiency"
NAME_CTF_STABILITY = "CTF stability"
NAME_MICROGRAPH_CLEANER = "Micrograph cleaner"
NAME_MAPQ = "MapQ"
NAME_CONVERSION_PDB_MAP = "Conversion PDB to map"
NAME_FSCQ = "FSC-Q"
NAME_MULTIMODEL = "Multimodel"
NAME_PHENIX = "Phenix"
NAME_EMRINGER = "EMRinger"
NAME_DAQ = "DAQ"
NAME_XLM = "XLM"
NAME_SAXS = "SAXS"
NAME_TILT_PAIR = "Tilt pair"

################################# LINKS ##################################

EMDB_LINK = "https://www.ebi.ac.uk/emdb/%s/"
PDB_LINK = "https://www.ebi.ac.uk/pdbe/entry/pdb/%s/"

BFACTOR_GUINIER_DOI = "https://doi.org/10.1016/j.jmb.2003.07.013"
DEEPRES_DOI = "https://doi.org/10.1107/S2052252519011692"
LOCBFACTOR_LOCOCCUPANCY_DOI = "https://doi.org/10.1038/s41467-021-21509-5"
DEEPHAND_DOI = "https://doi.org/10.1016/j.jsb.2022.107915"
GLOBALRES_DOI = "https://doi.org/10.1016/j.pbiomolbio.2016.09.005"
FSCPERMUTATION_DOI = "https://doi.org/10.1016/j.jsb.2020.107579"
BLOCRES_DOI = "https://doi.org/10.1016/j.jsb.2013.08.002"
RESMAP_DOI = "https://doi.org/10.1038/nmeth.2727"
MONORES_DOI = "https://doi.org/10.1016/j.str.2017.12.018"
MONODIR_DOI = "https://doi.org/10.1038/s41467-019-13742-w"
FSO_DOI = "https://doi.org/10.1038/s41592-023-01874-3"
FSC3D_DOI = "https://doi.org/10.1038/nmeth.4347"
COMPARE_REPROJECTIONS_DOI = "http://dx.doi.org/10.1109/TPAMI.2012.259"
CLASSANALYSES_LINK = "https://i2pc.es/coss/Articulos/Sorzano2014.pdf"
NEWCLASSIFICATION_DOI = "https://doi.org/10.1109/tpami.2016.2627573"
SIMILARITY_MEASURES_DOI = "https://doi.org/10.1016/j.jsb.2015.01.009"
ALIGNABILITY_SMOOTHNESS_DOI = "https://doi.org/10.1016/j.jsb.2021.107771"
MULTIREF_ALIGNABILITY_1_DOI = "https://doi.org/10.1038/srep21626"
MULTIREF_ALIGNABILITY_2_DOI = "https://doi.org/10.1038/s41598-017-06526-z"
RELION_ALIGNMENT_AND_CLASSIFICATION_DOI = "https://doi.org/10.1016%2Fj.jmb.2011.11.010"
CRYOSPARC_ALIGNMENT_DOI = "https://doi.org/10.1038/s41592-020-00990-8"
VALIDATE_OVERFITTING_DOI = "https://doi.org/10.3934/biophy.2015.1.21"
ANGULAR_DISTR_EFFICIENCY_DOI = "https://doi.org/10.1038/s41467-017-00782-3"
SAMPLING_COMPENS_FACTOR_1_DOI = "https://doi.org/10.1016/j.pbiomolbio.2019.09.002"
SAMPLING_COMPENS_FACTOR_2_DOI = "https://doi.org/10.1016/j.pbiomolbio.2020.06.003"
CTF_STABILITY_DOI = "https://doi.org/10.1016/j.jsb.2023.108030"
MICROGRAPH_CLEANER_DOI = "https://doi.org/10.1016/j.jsb.2020.107498"
PHENIX_DOI = "https://doi.org/10.1107/S2059798318009324"
FSCQ_DOI = "https://doi.org/10.1038/s41467-020-20295-w"
MULTIMODEL_DOI = "https://doi.org/10.1016/j.str.2018.10.003"
MAPQ_DOI = "https://doi.org/10.1038/s41592-020-0731-1"
EMRINGER_DOI = "https://doi.org/10.1038/nmeth.3541"
DAQ_DOI = "https://doi.org/10.1038/s41592-022-01574-4"
XLM_DOI = "https://doi.org/10.1016/j.str.2020.05.012"
SAXS_DOI = "https://doi.org/10.1093/bioinformatics/bty985"
TILT_PAIR_VALIDATION_DOI = "https://doi.org/10.1016/j.jmb.2011.09.008"
VRS_DOI = "https://doi.org/10.1039/D2FD00059H"
HELP_WEBSITE_LINK = "https://biocomp.cnb.csic.es/EMValidationService/help/"

####################### TERMINAL MESSAGES CONSTANTS #######################
PRINT_PROTOCOL_ABORTED = "PROTOCOL MANUALLY ABORTED"

####################### REPORT MESSAGES CONSTANTS #######################
# Summary
OK_MESSAGE = "{\\color{blue} OK}"
WARNINGS_MESSAGE = "{\\color{red} %d warnings}"
NOT_APPLY_MESSAGE = "{\\color{brown} Does not apply}"
ERROR_MESSAGE = "{\\color{red} Could not be measured}"
ERROR_CONVERT_MESSAGE = "{\\color{red} Could not be converted}"
ERROR_ABORTED_MESSAGE = "{\\color{red} MANUALLY ABORTED}"

# STATUS MESSAGES
STATUS = "\\textbf{STATUS}: "
STATUS_OK = STATUS + OK_MESSAGE + "\\\\ \n\n"
STATUS_NOT_APPLY = STATUS + NOT_APPLY_MESSAGE + "\\\\ \n\n"
STATUS_ERROR_MESSAGE = STATUS + ERROR_MESSAGE + "\\\\ \n\n"
STATUS_ERROR_CONVERT_MESSAGE = STATUS + ERROR_CONVERT_MESSAGE + "\\\\ \n\n"
STATUS_ERROR_ABORTED_MESSAGE = STATUS + ERROR_ABORTED_MESSAGE + "\\\\ \n\n"

# RESULT SECTION MESSAGES
ERROR_MESSAGE_PROTOCOL_FAILED = "{\\color{red} \\textbf{ERROR: The protocol failed.}}\\\\ \n\n"
ERROR_MESSAGE_PROTOCOL_X_FAILED = "{\\color{red} \\textbf{ERROR: The protocol %s failed.}}\\\\ \n\n"
ERROR_MESSAGE_NOT_BINARY = "{\\color{red} \\textbf{ERROR: Cannot find the binary}}\\\\ \n\n"
ERROR_MESSAGE_NOT_CLASSES = "{\\color{red} \\textbf{ERROR: Cannot find the output classes.}}\\\\ \n\n"
ERROR_MESSAGE_EMPTY_VOL = "{\\color{red} \\textbf{ERROR: The volume is empty.}}\\\\ \n\n"
ERROR_MESSAGE_NO_RESULTS = "{\\color{red} \\textbf{ERROR: The protocol did not produce any result.}}\\\\ \n\n"
ERROR_MESSAGE_ABORTED = "{\\color{red} \\textbf{ERROR: The protocol could not be finished because it was manually aborted.}}\\\\ \n\n"
ERROR_MESSAGE_CHECK_FITTED_FAILED = "{\\color{red} \\textbf{The protocol to check whether the model and map are aligned has failed. Since we cannot check if they are properly aligned, some problems or bad results may occur when running the Level A analysis due to misalignment.}}\\\\ \n\n"

NOT_APPY_NO_RESOLUTION = "{\\color{brown} This method cannot be applied to maps with no resolution reported.}\\\\ \n\n"
NOT_APPLY_BETTER_RESOLUTION = "{\\color{brown} This method cannot be applied to maps with a resolution better than %d\\AA.}\\\\ \n\n"
NOT_APPLY_WORSE_RESOLUTION = "{\\color{brown} This method cannot be applied to maps with a resolution worse than %d\\AA.}\\\\ \n\n"


SUMMARY_WARNINGS_TITLE = "\\textbf{\\underline{Summary of the warnings across sections.}}\\\\ \n\n\n"
PROPERLY_FITTED = "Map and model seem to be properly aligned."
FITTED_NEW_ORIGIN = "Map and model do not seem to be properly aligned. However, we found an origin of coordinates for which there is a better alignment. All level A analyses from here will take %s as the origin of coordinates."
NOT_FOUND_NEW_FITTED = "Map and model do not seem to be properly aligned. However, we have not found any origin of coordinates that allows a good alignment. Level A analyses will be skipped."




